### ISSUE TITLE
Compile_occurrencePt_datasets.R - unfinished section needs to be fixed

### ISSUE THREAD

**Issue by eb-bruns** [MortonArb-ForestEcology/Tree_Distribution_Database#1]
## separate single iDigBio lat/long column into lat and long (working):
 idigbio <- idigbio %>% separate("lat-long", c("lat", "long"), sep=",", fill="right", extra="merge")
    unique(idigbio$lat)
## help ###: Remove everything but the number in lat and long columns in idigbio:
  idigbio1$lat <- gsub("{\\\"lat\\\":","",idigbio$lat) # difficult b/c escape characters are part of text to be removed

**Comment by crollinson** [comment]
Can you put some screen grabs or printouts of what the error you're getting and/or what the inputs/outputs look like?  I can't tell enough about what things look like to make sense of this just from the line of code that isn't work.

**Comment by doctoretdiez** [comment]
I made some changes to the code. See if it's what you were hoping for once the push updates.
